# Generated by Django 4.0.2 on 2022-02-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_graphicards_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicards',
            name='Rep',
            field=models.FilePathField(path='/static/images'),
        ),
    ]
