# Generated by Django 4.0.2 on 2022-02-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_graphicards_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicards',
            name='file_name',
            field=models.CharField(default='145', max_length=30),
        ),
        migrations.AlterField(
            model_name='graphicards',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
