# Generated by Django 4.0.2 on 2022-02-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
