# Generated by Django 4.0.2 on 2022-02-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphicards',
            old_name='Price',
            new_name='price',
        ),
    ]
