# Generated by Django 4.0.2 on 2022-02-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0021_rename_price_graphicards_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graphicards',
            old_name='Rep',
            new_name='image',
        ),
    ]
